# Generated by Django 5.0.2 on 2024-08-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_name_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accredited_courses',
            field=models.BooleanField(default=False),
        ),
    ]
