# Generated by Django 5.0.2 on 2024-08-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_accredited_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='accredited_courses',
        ),
    ]
